[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx tsc", "npx vite build"]

[phases.start]
cmd = "node server.js"

[variables]
NODE_ENV = "production"
PORT = "8080"