[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["echo 'Skipping build for test'"]

[phases.start]
cmd = "node test.js"

[variables]
NODE_ENV = "production"
PORT = "8080"