[variables]
NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x", "openssl"]

[phases.install]
cmds = ["npm ci --production=false"]

[phases.build]
cmds = ["npm run compile", "npm run build"]

[start]
cmd = "npm start"