[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 120
healthcheckInterval = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
numReplicas = 1

[environment]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[build.env]
NODE_VERSION = "20"
NPM_VERSION = "9"

[deploy.env]
# Database connection optimizations
DB_CONNECTION_TIMEOUT = "10000"
DB_POOL_MAX = "10"
DB_POOL_MIN = "1"

# Application optimizations
NODE_OPTIONS = "--max-old-space-size=512"

[experimental]
deployments = true