[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 300
healthcheckInterval = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
numReplicas = 1

[environment]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
NIXPACKS_NODE_VERSION = "20"

[build.env]
NIXPACKS_NODE_VERSION = "20"
NODE_VERSION = "20"

[deploy.env]
# Force Node 20 usage
NIXPACKS_NODE_VERSION = "20"
NODE_VERSION = "20"

# Database connection optimizations
DB_CONNECTION_TIMEOUT = "10000"
DB_POOL_MAX = "10"
DB_POOL_MIN = "1"

# Application optimizations
NODE_OPTIONS = "--max-old-space-size=512"